spring.application.name=petshop

# Banco H2 em memória (desenvolvimento)
spring.datasource.url=jdbc:h2:mem:petshop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
